name: mirrorchyan

on:
  push:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Version Name
        id: version_name
        run: |
          data=$(cat resource/version.json)
          version=$(echo $data | jq -r .last_updated)
          
          activity_time=$(echo $data | jq -r .activity.time)
          gacha_time=$(echo $data | jq -r .gacha.time)
          if [ $activity_time -ge $gacha_time ]; then
            release_note=$(echo $data | jq -r .activity.name)
            release_note=$(echo $data | jq -r .gacha.pool)
          else
            release_note=$(echo $data | jq -r .gacha.pool)
          fi
          
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"
          echo "release_note=$release_note" | tee -a "$GITHUB_OUTPUT"
